baseURL = "https://zuff.dev"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "m10c"

# The browser tab name
title = "Mike Zuffoletti"


[params]
  author = "Mike Zuffoletti"
  description = "Software Engineer"
  favicon = "images/favicon-32x32.png"
  avatar = "images/headshot-bonneville.jpg"

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "running"
    name = "Running"
    url = "/running/"
    weight = 4

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/mikezuff"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/michael-zuffoletti-903b1a3"
